controller_frequency: 10.0
planner_patience: 1.0
controller_patience: 5.0
clearing_rotation_allowed: false
planner_frequency: 1.0

TrajectoryPlannerROS:
  max_vel_x: 0.03
  min_vel_x: 0
  max_rotational_vel: 0.7
  min_in_place_rotational_vel: 0.1
  acc_lim_th: 0.75
  acc_lim_x: 0.50
  acc_lim_y: 0.50

  holonomic_robot: false
  yaw_goal_tolerance: 3.14
  xy_goal_tolerance: 0.1
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  sim_time: 3.0
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05

  vx_samples: 6
  vtheta_samples: 20
  dwa: false

