local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 5.0
  static_map: true
  #map_topic: Global_Cost
  rolling_window: true
  width: 2.0
  height: 2.0
  resolution: 0.01
